
development:
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  database: <%= Rails.application.credentials[:database] %>
  username: <%= Rails.application.credentials[:username] %>
  password: <%= Rails.application.credentials[:password] %>
  host: <%= Rails.application.credentials[:host] %>
  port: <%= Rails.application.credentials[:port] %>