local:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>

production:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>

production_dev:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>

development:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>


test:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>

test_dev:
  solr:
    hostname: <%= Rails.application.credentials[:solr_hostname] %>
    port: <%= Rails.application.credentials[:solr_port] %>
    log_level: WARNING
    path: <%= Rails.application.credentials[:solr_path] %>